In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
data = pd.read_excel('../C题附件/附件1.xlsx')

In [4]:
data.describe()

,room_name,address_2nd,HEAT,IN_FLOW,FLOW_SPEED,IN_TEMPERATURE,OUT_TEMPERATURE,ROOM_TEMPERATURE,ROOM_SET_TEMPERATURE,POWER,RUNNING_STATE,dtemp
count,294977.000000,2.949770e+05,294977.000000,294977.000000,294977.000000,294977.000000,294977.000000,293849.000000,293847.000000,294977.000000,294977.0,294977.000000
mean,303.352285,1.531114e+07,17262.490787,2923.016621,0.284916,41.435701,36.005745,12.515022,19.510381,1.738939,0.0,5.429956
std,143.619730,2.323390e+02,7601.492988,1679.991216,0.208720,12.374984,10.128511,8.485760,13.016286,1.136263,0.0,4.017351
min,101.000000,1.531080e+07,3.850000,0.320000,0.000000,6.600000,0.000000,0.000000,0.000000,0.000000,0.0,-15.450000
25%,202.000000,1.531085e+07,15171.070000,2111.970000,0.160000,34.470000,31.510000,0.000000,0.000000,0.880000,0.0,3.220000
50%,303.000000,1.531120e+07,17855.780000,2581.740000,0.260000,47.420000,40.340000,17.100000,28.000000,1.940000,0.0,5.390000
75%,405.000000,1.531134e+07,21108.040000,3896.280000,0.430000,49.480000,42.920000,18.700000,28.000000,2.430000,0.0,7.670000
max,506.000000,1.531148e+07,45769.290000,7489.640000,2.400000,55.110000,50.600000,26.800000,35.000000,62.750000,0.0,28.560000

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 294977 entries, 0 to 294976
Data columns (total 16 columns):
building_name           294977 non-null object
unit_name               294977 non-null object
room_name               294977 non-null int64
address_2nd             294977 non-null int64
HEAT                    294977 non-null float64
IN_FLOW                 294977 non-null float64
FLOW_SPEED              294977 non-null float64
IN_TEMPERATURE          294977 non-null float64
OUT_TEMPERATURE         294977 non-null float64
ROOM_TEMPERATURE        293849 non-null float64
ROOM_SET_TEMPERATURE    293847 non-null float64
OPEN_STATUS             293847 non-null object
POWER                   294977 non-null float64
RUNNING_STATE           294977 non-null int64
SYS_READ_TIME           294977 non-null object
dtemp                   294977 non-null float64
dtypes: float64(9), int64(3), object(4)
memory usage: 36.0+ MB